apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      serviceAccountName: my-service-account
      containers:
        - name: auth-service
          image: atalayozyldrm/auth-service:latest
          ports:
            - containerPort: 3000

